KnowledgeManagerSystem/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import urls as auth_url
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('documents.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include((auth_url, 'authentication'), 'authentication')),
    path('profiles/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path

from .views import *

app_name = 'accounts'

urlpatterns = [
	# Security
	path('check-file-access-permission/<path:request_path_uri>', MediaFileAccessController.as_view(), name='media_access_control'),

	path('profile/list', ProfileListView.as_view(), name='profile_list'),
	path('profile/add', ProfileCreateView.as_view(), name='profile_create'),
	path('profile/<pk>', ProfileDetailsView.as_view(), name='profile_details'),
	path('profile/edit/<pk>', ProfileUpdateView.as_view(), name='profile_update'),
	path('profile/delete/<pk>', ProfileDeleteView.as_view(), name='profile_delete'),
]

documents/urls.py
from django.urls import path

from .views import *

app_name = 'documents'

urlpatterns = [
	path('attachment/<pk>/add', DocumentAttachmentCreateView.as_view(), name='attach_create'),
	path('core_attachment/<pk>/add', CoreAttachmentCreateView.as_view(), name='core_attach_create'),

	path('', HomeView.as_view(), name='home'),

	path('center/list', CenterListView.as_view(), name='center_list'),
	path('center/add', CenterCreateView.as_view(), name='center_create'),
	path('center/<pk>', CenterDetailsView.as_view(), name='center_details'),
	path('center/edit/<pk>', CenterUpdateForm.as_view(), name='center_update'),
	path('center/delete/<pk>', CenterDeleteView.as_view(), name='center_delete'),

	path('article/list', ArticleListView.as_view(), name='article_list'),
	path('article/add', ArticleCreateView.as_view(), name='article_create'),
	path('article/<pk>', ArticleDetailsView.as_view(), name='article_details'),
	path('article/edit/<pk>', ArticleUpdateForm.as_view(), name='article_update'),
	path('article/delete/<pk>', ArticleDeleteView.as_view(), name='article_delete'),

	path('resume/list', ResumeListView.as_view(), name='resume_list'),
	path('resume/add', ResumeCreateView.as_view(), name='resume_create'),
	path('resume/<pk>', ResumeDetailsView.as_view(), name='resume_details'),
	path('resume/edit/<pk>', ResumeUpdateForm.as_view(), name='resume_update'),
	path('resume/delete/<pk>', ResumeDeleteView.as_view(), name='resume_delete'),

	path('book/list', BookListView.as_view(), name='book_list'),
	path('book/add', BookCreateView.as_view(), name='book_create'),
	path('book/<pk>', BookDetailsView.as_view(), name='book_details'),
	path('book/edit/<pk>', BookUpdateForm.as_view(), name='book_update'),
	path('book/delete/<pk>', BookDeleteView.as_view(), name='book_delete'),

	path('experience/list', ExperienceListView.as_view(), name='experience_list'),
	path('experience/add', ExperienceCreateView.as_view(), name='experience_create'),
	path('experience/<pk>', ExperienceDetailsView.as_view(), name='experience_details'),
	path('experience/edit/<pk>', ExperienceUpdateForm.as_view(), name='experience_update'),
	path('experience/delete/<pk>', ExperienceDeleteView.as_view(), name='experience_delete'),

	path('idea/list', IdeaListView.as_view(), name='idea_list'),
	path('idea/add', IdeaCreateView.as_view(), name='idea_create'),
	path('idea/<pk>', IdeaDetailsView.as_view(), name='idea_details'),
	path('idea/edit/<pk>', IdeaUpdateForm.as_view(), name='idea_update'),
	path('idea/delete/<pk>', IdeaDeleteView.as_view(), name='idea_delete'),

	path('thesis/list', ThesisListView.as_view(), name='thesis_list'),
	path('thesis/add', ThesisCreateView.as_view(), name='thesis_create'),
	path('thesis/<pk>', ThesisDetailsView.as_view(), name='thesis_details'),
	path('thesis/edit/<pk>', ThesisUpdateForm.as_view(), name='thesis_update'),
	path('thesis/delete/<pk>', ThesisDeleteView.as_view(), name='thesis_delete'),

	path('seminar/list', SeminarListView.as_view(), name='seminar_list'),
	path('seminar/add', SeminarCreateView.as_view(), name='seminar_create'),
	path('seminar/<pk>', SeminarDetailsView.as_view(), name='seminar_details'),
	path('seminar/edit/<pk>', SeminarUpdateForm.as_view(), name='seminar_update'),
	path('seminar/delete/<pk>', SeminarDeleteView.as_view(), name='seminar_delete'),

	path('workshop/list', WorkshopListView.as_view(), name='workshop_list'),
	path('workshop/add', WorkshopCreateView.as_view(), name='workshop_create'),
	path('workshop/<pk>', WorkshopDetailsView.as_view(), name='workshop_details'),
	path('workshop/edit/<pk>', WorkshopUpdateForm.as_view(), name='workshop_update'),
	path('workshop/delete/<pk>', WorkshopDeleteView.as_view(), name='workshop_delete'),

	path('conference/list', ConferenceListView.as_view(), name='conference_list'),
	path('conference/add', ConferenceCreateView.as_view(), name='conference_create'),
	path('conference/<pk>', ConferenceDetailsView.as_view(), name='conference_details'),
	path('conference/edit/<pk>', ConferenceUpdateForm.as_view(), name='conference_update'),
	path('conference/delete/<pk>', ConferenceDeleteView.as_view(), name='conference_delete'),

	path('visit/list', VisitListView.as_view(), name='visit_list'),
	path('visit/add', VisitCreateView.as_view(), name='visit_create'),
	path('visit/<pk>', VisitDetailsView.as_view(), name='visit_details'),
	path('visit/edit/<pk>', VisitUpdateForm.as_view(), name='visit_update'),
	path('visit/delete/<pk>', VisitDeleteView.as_view(), name='visit_delete'),

	path('project/list', ProjectListView.as_view(), name='project_list'),
	path('project/add', ProjectCreateView.as_view(), name='project_create'),
	path('project/<pk>', ProjectDetailsView.as_view(), name='project_details'),
	path('project/edit/<pk>', ProjectUpdateForm.as_view(), name='project_update'),
	path('project/delete/<pk>', ProjectDeleteView.as_view(), name='project_delete'),

	path('report/list', ReportListView.as_view(), name='report_list'),
	path('report/add', ReportCreateView.as_view(), name='report_create'),
	path('report/<pk>', ReportDetailsView.as_view(), name='report_details'),
	path('report/edit/<pk>', ReportUpdateForm.as_view(), name='report_update'),
	path('report/delete/<pk>', ReportDeleteView.as_view(), name='report_delete'),

	path('manual/list', ManualListView.as_view(), name='manual_list'),
	path('manual/add', ManualCreateView.as_view(), name='manual_create'),
	path('manual/<pk>', ManualDetailsView.as_view(), name='manual_details'),
	path('manual/edit/<pk>', ManualUpdateForm.as_view(), name='manual_update'),
	path('manual/delete/<pk>', ManualDeleteView.as_view(), name='manual_delete'),

	path('order/list', OrderListView.as_view(), name='order_list'),
	path('order/add', OrderCreateView.as_view(), name='order_create'),
	path('order/<pk>', OrderDetailsView.as_view(), name='order_details'),
	path('order/edit/<pk>', OrderUpdateForm.as_view(), name='order_update'),
	path('order/delete/<pk>', OrderDeleteView.as_view(), name='order_delete'),

	path('journal/list', JournalListView.as_view(), name='journal_list'),
	path('journal/add', JournalCreateView.as_view(), name='journal_create'),
	path('journal/<pk>', JournalDetailsView.as_view(), name='journal_details'),
	path('journal/edit/<pk>', JournalUpdateForm.as_view(), name='journal_update'),
	path('journal/delete/<pk>', JournalDeleteView.as_view(), name='journal_delete'),


	path('future/list', FutureListView.as_view(), name='future_list'),
	path('future/add', FutureCreateView.as_view(), name='future_create'),
	path('future/<pk>', FutureDetailsView.as_view(), name='future_details'),
	path('future/edit/<pk>', FutureUpdateForm.as_view(), name='future_update'),
	path('future/delete/<pk>', FutureDeleteView.as_view(), name='future_delete'),


	path('cowork/list', CoWorkListView.as_view(), name='cowork_list'),
	path('cowork/add', CoWorkCreateView.as_view(), name='cowork_create'),
	path('cowork/<pk>', CoWorkDetailsView.as_view(), name='cowork_details'),
	path('cowork/edit/<pk>', CoWorkUpdateForm.as_view(), name='cowork_update'),
	path('cowork/delete/<pk>', CoWorkDeleteView.as_view(), name='cowork_delete'),

	path('invention/list', InventionListView.as_view(), name='invention_list'),
	path('invention/add', InventionCreateView.as_view(), name='invention_create'),
	path('invention/<pk>', InventionDetailsView.as_view(), name='invention_details'),
	path('invention/edit/<pk>', InventionUpdateForm.as_view(), name='invention_update'),
	path('invention/delete/<pk>', InventionDeleteView.as_view(), name='invention_delete'),

	path('assessment/list', AssessmentListView.as_view(), name='assessment_list'),
	path('assessment/add', AssessmentCreateView.as_view(), name='assessment_create'),
	path('assessment/<pk>', AssessmentDetailsView.as_view(), name='assessment_details'),
	path('assessment/edit/<pk>', AssessmentUpdateForm.as_view(), name='assessment_update'),
	path('assessment/delete/<pk>', AssessmentDeleteView.as_view(), name='assessment_delete'),

	path('core/list', CoreListView.as_view(), name='core_list'),
	path('core/add', CoreCreateView.as_view(), name='core_create'),
	path('core/<pk>', CoreDetailsView.as_view(), name='core_details'),
	path('core/edit/<pk>', CoreUpdateForm.as_view(), name='core_update'),
	path('core/delete/<pk>', CoreDeleteView.as_view(), name='core_delete'),

	path('tech/list', TechListView.as_view(), name='tech_list'),
	path('tech/add', TechCreateView.as_view(), name='tech_create'),
	path('tech/<pk>', TechDetailsView.as_view(), name='tech_details'),
	path('tech/edit/<pk>', TechUpdateForm.as_view(), name='tech_update'),
	path('tech/delete/<pk>', TechDeleteView.as_view(), name='tech_delete'),

	path('company/list', CompanyListView.as_view(), name='company_list'),
	path('company/add', CompanyCreateView.as_view(), name='company_create'),
	path('company/<pk>', CompanyDetailsView.as_view(), name='company_details'),
	path('company/edit/<pk>', CompanyUpdateForm.as_view(), name='company_update'),
	path('company/delete/<pk>', CompanyDeleteView.as_view(), name='company_delete'),

	path('center_personnel/<center_pk>/add', CenterPersonnelCreateView.as_view(), name='center_personnel_create'),
	path('center_personnel/<center_pk>/edit/<pk>', CenterPersonnelUpdateForm.as_view(), name='center_personnel_update'),
	path('center_personnel/delete/<pk>', CenterPersonnelDeleteView.as_view(), name='center_personnel_delete'),

	path('center_project/<center_pk>/add', CenterProjectCreateView.as_view(), name='center_project_create'),
	path('center_project/<center_pk>/edit/<pk>', CenterProjectUpdateForm.as_view(), name='center_project_update'),
	path('center_project/delete/<pk>', CenterProjectDeleteView.as_view(), name='center_project_delete'),


	path('import/<document_type>', DocumenttBulkCreateView.as_view(), name='import'),
	path('ajax/', AjaxHandler.as_view(), name='ajax'),
]

documents/templates/attach_form.html
{% load jalali_date %}
{% load static %}
{% load humanize %}


<div id="form-attach-error-container-{{ obj.id }}" class="col-lg-12 d-none">
    <div class="card col-md-12 text-center" style="color: whitesmoke;background-color: lightcoral">
        <h1 id="form-attach-error-{{ obj.id }}"></h1>
    </div>
</div>
<div class="col-lg-12">
    <div><br></div>
</div>
<form id="form-attach-{{ object.id }}" class="m-t" role="form" method="post" action="{% url 'documents:attach_create' pk=object.id %}" enctype="multipart/form-data">
{% csrf_token %}
    <div class="row">
        <input type="text" class="form-control d-none" value="{{ project_doc_type }}" aria-describedby="name_label" name="project_doc_type">
        <input type="text" class="form-control d-none" value="{{ object.id }}" aria-describedby="name_label" name="document_id">
        <div class="input-group mb-2">
              <div class="custom-file">
                <label id="attach-{{ object.id }}-label" class="custom-file-label text-left" for="attach-{{ object.id }}"></label>
                  <input type="file" class="custom-file-input" name="file" id="attach-{{ object.id }}">
              </div>
        </div>
        <div class="input-group mb-2">
            <div class="input-group-append">
                <span class="input-group-text" id="description_label">توضیحات: </span>
            </div>
            <textarea name="description" type="text" class="form-control" id="description" aria-describedby="description_label" ></textarea>
        </div>
        <button type="submit" id="button-attach-{{ object.id }}" class="btn btn-lg btn-outline-primary"><i class="fa fa-plus"></i> افزودن</button>
    </div>
</form>

<script>
document.getElementById( 'attach-{{ object.id }}' ).addEventListener( 'change', showFileName_attach  );
function showFileName_attach ( event ) {
  var input = event.srcElement;
  var fileName = input.files[0].name;
  document.getElementById( 'attach-{{ object.id }}-label' ).textContent = fileName.substring(fileName.length - 20, fileName.length);
}

$('#form-attach-{{ object.id }}').submit(function (e) {
 if ($('#attach-{{ object.id }}').val() === '') {
     e.preventDefault();
     $('#form-attach-error-container-{{ obj.id }}').removeClass('d-none');
     $('#form-attach-error-{{ obj.id }}').text('هیچ فایلی انتخاب نشده است.');
 }
});
</script>

documents/templates/core_attach_form.html
{% load jalali_date %}
{% load static %}
{% load humanize %}

<div id="form-attach-error-container-{{ obj.id }}" class="col-lg-12 d-none">
    <div class="card col-md-12 text-center" style="color: whitesmoke;background-color: lightcoral">
        <h1 id="form-attach-error-{{ obj.id }}"></h1>
    </div>
</div>
<div class="col-lg-12">
    <div><br></div>
</div>
<form id="form-attach-{{ object.id }}" class="m-t" role="form" method="post" action="{% url 'documents:core_attach_create' pk=object.id %}" enctype="multipart/form-data">
{% csrf_token %}
    <div class="row">
        <input type="text" class="form-control d-none" value="{{ object.id }}" aria-describedby="name_label" name="document_id">
        <div class="input-group mb-2">
              <div class="custom-file">
                <label id="attach-{{ object.id }}-label" class="custom-file-label text-left" for="attach-{{ object.id }}"></label>
                  <input type="file" class="custom-file-input" name="file" id="attach-{{ object.id }}">
              </div>
        </div>
        <div class="input-group mb-2">
            <div class="input-group-append">
                <span class="input-group-text" id="description_label">توضیحات: </span>
            </div>
            <textarea name="description" type="text" class="form-control" id="description" aria-describedby="description_label" ></textarea>
        </div>
        <button type="submit" id="button-attach-{{ object.id }}" class="btn btn-lg btn-outline-primary"><i class="fa fa-plus"></i> افزودن</button>
    </div>
</form>

<script>
document.getElementById( 'attach-{{ object.id }}' ).addEventListener( 'change', showFileName_attach  );
function showFileName_attach ( event ) {
  var input = event.srcElement;
  var fileName = input.files[0].name;
  document.getElementById( 'attach-{{ object.id }}-label' ).textContent = fileName.substring(fileName.length - 20, fileName.length);
}
$('#form-attach-{{ object.id }}').submit(function (e) {

 if ($('#attach-{{ object.id }}').val() === '') {
     e.preventDefault();
     $('#form-attach-error-container-{{ obj.id }}').removeClass('d-none');
     $('#form-attach-error-{{ obj.id }}').text('هیچ فایلی انتخاب نشده است.');
 }
});
</script>

documents/templates/home.html
{% extends 'empty_base.html' %}
{% load staticfiles %}{% load widget_tweaks %}{% load i18n %}{% load jalali_date %}

{% block title %}خانه{% endblock %}

{% block content %}
    {%  has_perms user 'knowledge;' as has_knowledge_perm %}
    {%  has_perms user 'center;' as has_center_perm %}
    {%  has_perms user 'future;' as has_future_perm %}
    {%  has_perms user 'resume;' as has_resume_perm %}
	<div class="text-center animated fadeInDown" style="font-family: VazirFD">
        <div class="row">
            <div class="col-lg-2">
                <div>
                    <img src="{% static 'img/sepah_balck.png' %}" style="width: 200px;alignment: center"/>
                </div>
            </div>
            <div class="col-lg-8">
                <h1 style="font-family: 'B Nazanin';font-size: 50px;font-weight: bolder">سامانه جامع مدیریت یکپارچه علم و فناوری- سمیع</h1>
                <h1 style="font-family: 'B Nazanin';font-size: 40px;font-weight: bolder">سازمان تحقیقات و جهاد خودکفایی ندسا</h1>
                <button class="btn btn-lg btn-primary" style="width: 600px;"></button>
            </div>
            <div class="col-lg-2">
                <div>
                    <img src="{% static 'img/logo.png' %}" style="width: 230px; alignment: center"/>
                </div>
            </div>
        </div>
        <br>
        <br>
        <div class="row">
            <div class="col-lg-2">
            </div>
            {% if user.is_superuser or has_knowledge_perm %}
            <div class="col-lg-3 text-center" href="{% url 'documents:article_list' %}">
                <div class="text-center">
                    <a href="{% url 'documents:article_list' %}"><img src="{% static 'img/knowledge.png' %}" style="height: 350px; alignment: center"/></a>
                </div>
{#                <a href="{% url 'documents:article_list' %}"><h3>مدیریت دانش</h3></a>#}
            </div>
            {% endif %}
        <div class="col-lg-2">
            </div>
        {% if user.is_superuser or has_center_perm %}
            <div class="col-lg-3 text-center" href="{% url 'documents:project_list' %}">
                <div class="text-center">
                    <a href="{% url 'documents:core_list' %}"><img src="{% static 'img/development.png' %}" style="height: 350px; alignment: center"/></a>
                </div>
{#                <a href="{% url 'documents:core_list' %}"><h3>رشد، خلاقیت و نوآوری</h3></a>#}
            </div>
        {% endif %}
            <div class="col-lg-2">
            </div>
        </div>
        <div class="row">
            <div class="col-lg-2">
            </div>
            {% if user.is_superuser or has_future_perm %}
            <div class="col-lg-3 text-center" >
                <div class="text-center">
                    <a href="{% url 'documents:future_list' %}"><img src="{% static 'img/future.png' %}" style="height: 350px; alignment: center"/></a>
                </div>
{#                <a href="{% url 'documents:future_list' %}"><h3>آینده پژوهی و همکاری های علمی</h3></a>#}
            </div>
            {% endif %}
        <div class="col-lg-2">
            </div>
        {% if user.is_superuser or has_resume_perm %}
            <div class="col-lg-3 text-center" >
                <div class="text-center">
                    <a href="{% url 'documents:assessment_list' %}"><img src="{% static 'img/learning.png' %}" style="height: 350px; alignment: center"/></a>
                </div>
{#                <a href="{% url 'documents:assessment_list' %}"><h3>آموزش و امور محققین</h3></a>#}
            </div>
        {% endif %}
            <div class="col-lg-2">
            </div>
        </div>
	</div>
{% endblock %}

documents/templates/import.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% load jalali_date %}


{% block head_title %}افزودن گروهی {{ document_type }}{% endblock %}


{% block title-breadcrumb %}
	<div class="col-md-9">
    <br>
    <br>
		<ol class="breadcrumb">
			<li class="breadcrumb-item">
				<a>{{ document_type_section }}</a>
			</li>
			<li class="breadcrumb-item">
				<a href="{% url document_type_sub_section_url %}">فهرست {{ document_type_display }}</a>
			</li>
			<li class="breadcrumb-item active">
                <a>افزودن گروهی {{ document_type_display }}</a>
			</li>
		</ol>
	</div>

	<div class="col-md-3">
	</div>

{% endblock %}

{% block content %}
	<div class="row">

            {% if form.errors %}
                <div class="card col-md-12 text-center" style="color: whitesmoke;background-color: lightcoral">
                {% for field in form %}
                    {% for error in field.errors %}
                    <h1> {{ field.name }}: {{ error }} </h1>
                {% endfor %}
                {% endfor %}
                </div>
            {% endif %}
            {% for error in form.non_field_errors %}
                <div class="card col-md-12 text-center" style="color: whitesmoke;background-color: lightcoral">
                <h1> {{ error }} </h1>
                </div>
            {% endfor %}
<div class="col-lg-4 text-center">

</div>
<div class="col-lg-4 text-center">
            <form id="pr-form" class="m-t" id="project-form" role="form" method="post" enctype="multipart/form-data">
                {% csrf_token %}

                        <div><br></div>
                        <i class="fa fa-file-excel fa-10x"></i>
                                <h1><strong>فایل اکسل</strong></h1>
                <div><br></div>
                <div class="input-group mb-2" hidden>
                  <div class="input-group-append">
                    <span class="input-group-text required" id="type_label">نوع: </span>
                  </div>
                  <input type="text" class="form-control" value="{{ document_type }}" name="doc_type" aria-describedby="type_label" readonly>
                </div>
                <div class="input-group mb-2">
                      <div class="custom-file">
                        <label id="excel_file_label" class="custom-file-label text-left" for="excel_file_id"></label>
                          <input type="file" class="custom-file-input" name="excel_file" id="excel_file_id">
                      </div>
                    </div>
                <div><br></div>
                <div class="btn-group">
                        <button type="submit" class="btn btn-lg btn-outline-primary"><i class="fa fa-save"></i> بارگذاری </button>
                </div>

            </form>
</div>
    </div>
    <div class="col-lg-4 text-center">
    </div>
	<!-- Delete Modal -->

{% endblock %}

{% block scripts %}
	<script>
		var input_excel_file = document.getElementById( 'excel_file' );
    var infoArea_excel_file = document.getElementById( 'excel_file_label' );

    excel_file_id.addEventListener( 'change', showFileName_resume );
    function showFileName_resume( event ) {
      var input = event.srcElement;
      var fileName = input.files[0].name;
      infoArea_excel_file.textContent = fileName.substring(fileName.length - 20, fileName.length);
    }

	</script>
{% endblock %}