KnowledgeManagerSystem/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import urls as auth_url
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('documents.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include((auth_url, 'authentication'), 'authentication')),
    path('profiles/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path

from .views import *

app_name = 'accounts'

urlpatterns = [
	# Security
	path('check-file-access-permission/<path:request_path_uri>', MediaFileAccessController.as_view(), name='media_access_control'),

	path('profile/list', ProfileListView.as_view(), name='profile_list'),
	path('profile/add', ProfileCreateView.as_view(), name='profile_create'),
	path('profile/<pk>', ProfileDetailsView.as_view(), name='profile_details'),
	path('profile/edit/<pk>', ProfileUpdateView.as_view(), name='profile_update'),
	path('profile/delete/<pk>', ProfileDeleteView.as_view(), name='profile_delete'),
]

documents/urls.py
from django.urls import path

from .views import *

app_name = 'documents'

urlpatterns = [
	path('attachment/<pk>/add', DocumentAttachmentCreateView.as_view(), name='attach_create'),
	path('core_attachment/<pk>/add', CoreAttachmentCreateView.as_view(), name='core_attach_create'),

	path('', HomeView.as_view(), name='home'),

	path('center/list', CenterListView.as_view(), name='center_list'),
	path('center/add', CenterCreateView.as_view(), name='center_create'),
	path('center/<pk>', CenterDetailsView.as_view(), name='center_details'),
	path('center/edit/<pk>', CenterUpdateForm.as_view(), name='center_update'),
	path('center/delete/<pk>', CenterDeleteView.as_view(), name='center_delete'),

	path('article/list', ArticleListView.as_view(), name='article_list'),
	path('article/add', ArticleCreateView.as_view(), name='article_create'),
	path('article/<pk>', ArticleDetailsView.as_view(), name='article_details'),
	path('article/edit/<pk>', ArticleUpdateForm.as_view(), name='article_update'),
	path('article/delete/<pk>', ArticleDeleteView.as_view(), name='article_delete'),

	path('resume/list', ResumeListView.as_view(), name='resume_list'),
	path('resume/add', ResumeCreateView.as_view(), name='resume_create'),
	path('resume/<pk>', ResumeDetailsView.as_view(), name='resume_details'),
	path('resume/edit/<pk>', ResumeUpdateForm.as_view(), name='resume_update'),
	path('resume/delete/<pk>', ResumeDeleteView.as_view(), name='resume_delete'),

	path('book/list', BookListView.as_view(), name='book_list'),
	path('book/add', BookCreateView.as_view(), name='book_create'),
	path('book/<pk>', BookDetailsView.as_view(), name='book_details'),
	path('book/edit/<pk>', BookUpdateForm.as_view(), name='book_update'),
	path('book/delete/<pk>', BookDeleteView.as_view(), name='book_delete'),

	path('experience/list', ExperienceListView.as_view(), name='experience_list'),
	path('experience/add', ExperienceCreateView.as_view(), name='experience_create'),
	path('experience/<pk>', ExperienceDetailsView.as_view(), name='experience_details'),
	path('experience/edit/<pk>', ExperienceUpdateForm.as_view(), name='experience_update'),
	path('experience/delete/<pk>', ExperienceDeleteView.as_view(), name='experience_delete'),

	path('idea/list', IdeaListView.as_view(), name='idea_list'),
	path('idea/add', IdeaCreateView.as_view(), name='idea_create'),
	path('idea/<pk>', IdeaDetailsView.as_view(), name='idea_details'),
	path('idea/edit/<pk>', IdeaUpdateForm.as_view(), name='idea_update'),
	path('idea/delete/<pk>', IdeaDeleteView.as_view(), name='idea_delete'),

	path('thesis/list', ThesisListView.as_view(), name='thesis_list'),
	path('thesis/add', ThesisCreateView.as_view(), name='thesis_create'),
	path('thesis/<pk>', ThesisDetailsView.as_view(), name='thesis_details'),
	path('thesis/edit/<pk>', ThesisUpdateForm.as_view(), name='thesis_update'),
	path('thesis/delete/<pk>', ThesisDeleteView.as_view(), name='thesis_delete'),

	path('seminar/list', SeminarListView.as_view(), name='seminar_list'),
	path('seminar/add', SeminarCreateView.as_view(), name='seminar_create'),
	path('seminar/<pk>', SeminarDetailsView.as_view(), name='seminar_details'),
	path('seminar/edit/<pk>', SeminarUpdateForm.as_view(), name='seminar_update'),
	path('seminar/delete/<pk>', SeminarDeleteView.as_view(), name='seminar_delete'),

	path('workshop/list', WorkshopListView.as_view(), name='workshop_list'),
	path('workshop/add', WorkshopCreateView.as_view(), name='workshop_create'),
	path('workshop/<pk>', WorkshopDetailsView.as_view(), name='workshop_details'),
	path('workshop/edit/<pk>', WorkshopUpdateForm.as_view(), name='workshop_update'),
	path('workshop/delete/<pk>', WorkshopDeleteView.as_view(), name='workshop_delete'),

	path('conference/list', ConferenceListView.as_view(), name='conference_list'),
	path('conference/add', ConferenceCreateView.as_view(), name='conference_create'),
	path('conference/<pk>', ConferenceDetailsView.as_view(), name='conference_details'),
	path('conference/edit/<pk>', ConferenceUpdateForm.as_view(), name='conference_update'),
	path('conference/delete/<pk>', ConferenceDeleteView.as_view(), name='conference_delete'),

	path('visit/list', VisitListView.as_view(), name='visit_list'),
	path('visit/add', VisitCreateView.as_view(), name='visit_create'),
	path('visit/<pk>', VisitDetailsView.as_view(), name='visit_details'),
	path('visit/edit/<pk>', VisitUpdateForm.as_view(), name='visit_update'),
	path('visit/delete/<pk>', VisitDeleteView.as_view(), name='visit_delete'),

	path('project/list', ProjectListView.as_view(), name='project_list'),
	path('project/add', ProjectCreateView.as_view(), name='project_create'),
	path('project/<pk>', ProjectDetailsView.as_view(), name='project_details'),
	path('project/edit/<pk>', ProjectUpdateForm.as_view(), name='project_update'),
	path('project/delete/<pk>', ProjectDeleteView.as_view(), name='project_delete'),

	path('report/list', ReportListView.as_view(), name='report_list'),
	path('report/add', ReportCreateView.as_view(), name='report_create'),
	path('report/<pk>', ReportDetailsView.as_view(), name='report_details'),
	path('report/edit/<pk>', ReportUpdateForm.as_view(), name='report_update'),
	path('report/delete/<pk>', ReportDeleteView.as_view(), name='report_delete'),

	path('manual/list', ManualListView.as_view(), name='manual_list'),
	path('manual/add', ManualCreateView.as_view(), name='manual_create'),
	path('manual/<pk>', ManualDetailsView.as_view(), name='manual_details'),
	path('manual/edit/<pk>', ManualUpdateForm.as_view(), name='manual_update'),
	path('manual/delete/<pk>', ManualDeleteView.as_view(), name='manual_delete'),

	path('order/list', OrderListView.as_view(), name='order_list'),
	path('order/add', OrderCreateView.as_view(), name='order_create'),
	path('order/<pk>', OrderDetailsView.as_view(), name='order_details'),
	path('order/edit/<pk>', OrderUpdateForm.as_view(), name='order_update'),
	path('order/delete/<pk>', OrderDeleteView.as_view(), name='order_delete'),

	path('journal/list', JournalListView.as_view(), name='journal_list'),
	path('journal/add', JournalCreateView.as_view(), name='journal_create'),
	path('journal/<pk>', JournalDetailsView.as_view(), name='journal_details'),
	path('journal/edit/<pk>', JournalUpdateForm.as_view(), name='journal_update'),
	path('journal/delete/<pk>', JournalDeleteView.as_view(), name='journal_delete'),


	path('future/list', FutureListView.as_view(), name='future_list'),
	path('future/add', FutureCreateView.as_view(), name='future_create'),
	path('future/<pk>', FutureDetailsView.as_view(), name='future_details'),
	path('future/edit/<pk>', FutureUpdateForm.as_view(), name='future_update'),
	path('future/delete/<pk>', FutureDeleteView.as_view(), name='future_delete'),


	path('cowork/list', CoWorkListView.as_view(), name='cowork_list'),
	path('cowork/add', CoWorkCreateView.as_view(), name='cowork_create'),
	path('cowork/<pk>', CoWorkDetailsView.as_view(), name='cowork_details'),
	path('cowork/edit/<pk>', CoWorkUpdateForm.as_view(), name='cowork_update'),
	path('cowork/delete/<pk>', CoWorkDeleteView.as_view(), name='cowork_delete'),

	path('invention/list', InventionListView.as_view(), name='invention_list'),
	path('invention/add', InventionCreateView.as_view(), name='invention_create'),
	path('invention/<pk>', InventionDetailsView.as_view(), name='invention_details'),
	path('invention/edit/<pk>', InventionUpdateForm.as_view(), name='invention_update'),
	path('invention/delete/<pk>', InventionDeleteView.as_view(), name='invention_delete'),

	path('assessment/list', AssessmentListView.as_view(), name='assessment_list'),
	path('assessment/add', AssessmentCreateView.as_view(), name='assessment_create'),
	path('assessment/<pk>', AssessmentDetailsView.as_view(), name='assessment_details'),
	path('assessment/edit/<pk>', AssessmentUpdateForm.as_view(), name='assessment_update'),
	path('assessment/delete/<pk>', AssessmentDeleteView.as_view(), name='assessment_delete'),

	path('core/list', CoreListView.as_view(), name='core_list'),
	path('core/add', CoreCreateView.as_view(), name='core_create'),
	path('core/<pk>', CoreDetailsView.as_view(), name='core_details'),
	path('core/edit/<pk>', CoreUpdateForm.as_view(), name='core_update'),
	path('core/delete/<pk>', CoreDeleteView.as_view(), name='core_delete'),

	path('tech/list', TechListView.as_view(), name='tech_list'),
	path('tech/add', TechCreateView.as_view(), name='tech_create'),
	path('tech/<pk>', TechDetailsView.as_view(), name='tech_details'),
	path('tech/edit/<pk>', TechUpdateForm.as_view(), name='tech_update'),
	path('tech/delete/<pk>', TechDeleteView.as_view(), name='tech_delete'),

	path('company/list', CompanyListView.as_view(), name='company_list'),
	path('company/add', CompanyCreateView.as_view(), name='company_create'),
	path('company/<pk>', CompanyDetailsView.as_view(), name='company_details'),
	path('company/edit/<pk>', CompanyUpdateForm.as_view(), name='company_update'),
	path('company/delete/<pk>', CompanyDeleteView.as_view(), name='company_delete'),

	path('center_personnel/<center_pk>/add', CenterPersonnelCreateView.as_view(), name='center_personnel_create'),
	path('center_personnel/<center_pk>/edit/<pk>', CenterPersonnelUpdateForm.as_view(), name='center_personnel_update'),
	path('center_personnel/delete/<pk>', CenterPersonnelDeleteView.as_view(), name='center_personnel_delete'),

	path('center_project/<center_pk>/add', CenterProjectCreateView.as_view(), name='center_project_create'),
	path('center_project/<center_pk>/edit/<pk>', CenterProjectUpdateForm.as_view(), name='center_project_update'),
	path('center_project/delete/<pk>', CenterProjectDeleteView.as_view(), name='center_project_delete'),


	path('import/<document_type>', DocumenttBulkCreateView.as_view(), name='import'),
	path('ajax/', AjaxHandler.as_view(), name='ajax'),
]

documents/templates/report/report_detail.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% load jalali_date %}


{% block head_title %}جزئیات گزارش{% endblock %}


{% block title-breadcrumb %}
	<div class="col-md-9">
    <br>
    <br>
		<ol class="breadcrumb">
            <li class="breadcrumb-item">
				<a>مدیریت دانش</a>
			</li>
			<li class="breadcrumb-item">
                <a  href="{% url 'documents:report_list' %}" >فهرست گزارش ها</a>
			</li>
			<li class="breadcrumb-item active">
				<a href="{% url 'documents:report_details' object.id %}"><strong>جزئیات گزارش {{ object.name }}</strong></a>
			</li>
		</ol>
	</div>

	<div class="col-md-3">
		<div class="title-action float-right">
            <div class="btn-group">
                <a href="{% url 'documents:report_update' pk=object.id %}" class="btn btn-lg btn-outline-warning"><i class="fa fa-file-alt"></i> ویرایش</a>
			    <button data-toggle="modal" data-delete-what="{{ object.id }}" data-target="#delete-modal" class="btn btn-lg btn-outline-danger"><i class="fa fa-trash"></i> حذف </button>
            </div>
        </div>
	</div>
{% endblock %}

{% block content %}
	<div class="row">
        <div class="col-lg-12">
			<div class="col-lg-3 text-center">
				<div><br></div>
				<i class="fa fa-file-alt fa-10x"></i>
				<h1><strong>مشخصات</strong></h1>
			</div>
			<div class="card col-lg-9">
				<div><br></div>
				<h3><strong>عنوان: </strong>{{ object.title }}</h3>
				<h3><strong>شناسه: </strong>{{ object.organization_code }}</h3>
				<h3><strong>حوزه تخصصی: </strong>{{ object.field }}</h3>
				<h3><strong>تهیه کنندگان: </strong>
                {% for obj in object.producers.all %}
                        {{ obj.title }}-{{ obj.organization_code }},
                    {% endfor %}
                </h3>
				<h3><strong>پروژه مرتبط: </strong>{{ object.related_project }}</h3>
				<h3><strong>تاریخ ارائه: </strong>{{ object.presented_at | j_format_date:"%Y/%m/%d"  }}</h3>
				<h3><strong>مرکز تحقیقاتی: </strong>{{ object.center.title }}</h3>
                <h3><strong>توضیحات: </strong>{{ object.description }}</h3>
				<div><br></div>
			</div>
		</div>
		<div class="col-lg-12">
			<div class="col-lg-3 text-center">
				<div><br></div>
				<i class="fa fa-file-alt fa-10x"></i>
				<h1><strong>پیوست</strong></h1>
			</div>
			<div class="card col-lg-9">
				<div><br></div>
				<div class="input-group mb-2">
					<div class="input-group-append">
						<span class="input-group-text" id="pay_label"><i class="fa fa-file"></i>فایل های پیوست</span>
					</div>
					<input readonly type="text" class="form-control" aria-describedby="name_label">
				</div>
				<br>
				{% if not object.attachments.all.exists %}
					<br>
					<p class="text-center">تاکنون فایلی پیوست نشده است.</p>
				{% endif %}
				<div class="row">
				{% for file in object.attachments.all %}
					<div class="col-lg-3">
						<br>
						<h5>فایل: {{ file.file|truncatechars:20 }}</h5>
						<h5>توضیحات: {{ file.description }}</h5>
						<div class="btn-group">
						<a href="{{ file.file.url }}" class="btn btn-sm btn-outline-primary">
							دانلود
							<i class="fa fa-download"></i>
						</a>
							<button data-toggle="modal" data-target="#delete-attach-modal-{{ file.id }}" class="btn btn-sm btn-outline-danger"><i class="fa fa-trash-alt"></i> حذف </button>
						</div>
                        <div class="modal inmodal fade" id="delete-attach-modal-{{ file.id }}" tabindex="-1" role="dialog" aria-labelledby="file-exampleModalLabel" aria-hidden="true">
                            <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                            <span class="sr-only">بستن</span>
                                        </button>
                                        <h5 class="modal-title" id="file-exampleModalLabel">حذف پیوست</h5>
                                    </div>
                                    <div class="modal-body">
                                        <p class="float-right">
                                            آیا واقعا می خواهید فایل
                                            <code>
                                                <strong id="file-delete-name">{{ file.file }}</strong>
                                            </code>
                                            را حذف کنید؟
                                        </p>
                                    </div>
                                    <div class="modal-footer float-right">
                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">انصراف</button>
                                        <button type="button" onclick="attach_delete({{ file.id }})" class="btn btn-danger">حذف</button>
                                    </div>
                                </div>
                            </div>
                        </div>
					</div>
				{% endfor %}
				</div>
				<div><br></div>
                <div class="col-lg-12">
                <br>
                {% include 'attach_form.html' %}
                <div><br></div>
                </div>
			</div>

		</div>

    </div>
	<!-- Delete Modal -->
	<div class="modal inmodal fade" id="delete-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
		<div class="modal-dialog" role="document">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-label="Close">
						<span aria-hidden="true">&times;</span>
						<span class="sr-only">بستن</span>
					</button>
					<h5 class="modal-title" id="exampleModalLabel">حذف گزارش</h5>
				</div>
				<form method="post" id="delete-form" action="{% url 'documents:report_delete' pk=object.id %}">
					{% csrf_token %}
					<div class="modal-body">
						<p class="float-right">
							آیا واقعا می خواهید گزارش
							<code>
								<strong id="delete-name">{{ object.title }}</strong>
							</code>
							را حذف کنید؟
						</p>
					</div>
					<div class="modal-footer float-right">
						<button type="button" class="btn btn-secondary" data-dismiss="modal">انصراف</button>
						<button type="submit" class="btn btn-danger">حذف</button>
					</div>
				</form>
			</div>
		</div>
	</div>


{% endblock %}

{% block scripts %}
	<link href="{% static 'vendors/datatables/css/datatables.min.css' %}" rel="stylesheet">
	<script src="{% static 'vendors/datatables/js/datatables.min.js' %}"></script>
	<script src="{% static 'vendors/datatables/js/datatables.bootstrap4.min.js' %}"></script>

	<script>
        $(document).ready(function() {
            $("#attach-{{ object.id }}").modalForm({
                formURL: "{% url 'documents:attach_create' pk=object.id %}"
            });
        });
		var table;
		// this is the id of the form
		$("#delete-form").submit(function (e) {
			var form = $(this);
			var url = form.attr('action');

			$.ajax({
				type: "POST",
				url: url,
				data: form.serialize(), // serializes the form's elements.
				success: function (data) {
                    location.replace("{% url 'documents:report_list' %}");
				}
			});
			e.preventDefault(); // avoid to execute the actual submit of the form.
		});

        function attach_delete(id) {
            $.ajax({
                url: "{% url 'documents:ajax' %}",
                data: {
                    'request_type': 'delete_attachment',
                    'attachment_id': `${id}`,
                },
                contentType: 'application/json; charset=utf-8',
                dataType: 'json',
                success: function (data) {
                    location.reload();
                }
            });
        }
	</script>
{% endblock %}

documents/templates/report/report_list.html
{% extends 'base.html' %}
{% load static %}
{% load jalali_date %}


{% block head_title %}فهرست گزارش ها{% endblock %}

{% block title-breadcrumb %}
	<div class="col-md-10">
    <br>
    <br>
		<ol class="breadcrumb">
			<li class="breadcrumb-item">
				<a>مدیریت دانش</a>
			</li>
			<li class="breadcrumb-item active">
                <a  href="{% url 'documents:report_list' %}" >فهرست گزارش ها</a>
			</li>
		</ol>
	</div>

	<div class="col-md-2">
		<div class="title-action float-right">
            <div class="btn-group">
                <a href="{% url 'documents:report_create' %}" class="btn btn-outline-primary"><i class="fa small fa-plus"></i> <i class="fa fa-file-alt"></i> افزودن گزارش جدید</a>

            </div>
            </div>
	</div>
{% endblock %}

{% block content %}
	<div class="row">
    	<div class="col-lg-12">
			<div class="ibox ">
                <div class="ibox-title">
                    <h5>جستجوی پیشرفته گزارش ها</h5>
                    <div class="ibox-tools">
                            <a class="collapse-link">
                                <i class="fa fa-chevron-up"></i>
                            </a>
                            <a class="close-link">
                                <i class="fa fa-times"></i>
                            </a>
                        </div>
                </div>
                <div class="ibox-content">
                    <br>
                    <div class="row">
                            <div class="col-lg-1">
                            <label for="producer">تهیه کننده</label>
                            </div>
                            <div class="col-lg-3">
                            <input type="text" id="producer" name="producer">
                            </div>
                        <div class="col-lg-1">
                            <label for="center">مرکز</label>
                        </div>
                        <div class="col-lg-3">
                            <input type="text" id="center" name="center">
                        </div>
                        <div class="col-lg-1">
                            <label for="presentation_date">تاریخ ارائه</label>
                        </div>
                        <div class="col-lg-3">
                            <input type="text" id="presentation_date" name="presentation_date">
                        </div>
                    </div>
                    <br>
                </div>
            </div>
			<div class="table-responsive">
            	<br>
				<table class="table table-striped table-bordered table-hover dataTables-example">
					<thead>
					<tr>
						<th class="text-center" style="background-color: white;width: 7%">ردیف</th>
						<th class="text-center" style="background-color: white">عنوان</th>
						<th class="text-center" style="background-color: white">شناسه</th>
						<th class="text-center" style="background-color: white">حوزه</th>
                        <th class="text-center" style="background-color: white">تهیه کنندگان</th>
						<th class="text-center" style="background-color: white">تاریخ ارائه</th>
                        <th class="text-center" style="background-color: white">پروژه مرتبط</th>
						<th class="text-center" style="background-color: white">مرکز تحقیقاتی</th>
						<th class="text-center" style="background-color: white; width: 10%">عملیات</th>
					</tr>
					</thead>
					<tbody>

					{% for obj in object_list %}
						<tr id="c-tr-{{ obj.id }}"style="background-color: whitesmoke">
							<td class="align-middle text-center">{{ forloop.counter }}</td>
							<td class="align-middle text-center"><a href="{% url 'documents:report_details' pk=obj.id %}">{{ obj.title }}</a></td>
							<td class="align-middle text-center">{{ obj.organization_code }}</td>
							<td class="align-middle text-center">{{ obj.field }}</td>
							<td class="align-middle text-center">
                            {% for o in obj.producers.all %}
                                    {{ o.title }},
                                {% endfor %}
                            </td>
							<td class="align-middle text-center">{{ obj.presented_at | j_format_date:"%Y/%m/%d" }}</td>
							<td class="align-middle text-center">{{ obj.related_project }}</td>
							<td class="align-middle text-center">{{ obj.center.title }}</td>
							<td class="align-middle text-center">
								<div class="btn-group">
								<a href="{% url 'documents:report_update' pk=obj.id %}" class="btn btn-sm btn-outline-warning"><i class="fa small fa-pen"></i><i class="fa fa-cube"></i> ویرایش</a>
								<button data-cid="{{ obj.id }}" class="btn btn-sm btn-outline-danger m-l-sm" data-toggle="modal" data-target="#delete-modal"><i class="fa fa-trash"></i> حذف
								</button>
								</div>
							</td>
						</tr>
					{% endfor %}

					</tbody>

				</table>
			</div>
        </div>
	</div>

	<!-- Delete Modal -->
	<div class="modal inmodal fade" id="delete-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
		<div class="modal-dialog" role="document">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-label="Close">
						<span aria-hidden="true">&times;</span>
						<span class="sr-only">بستن</span>
					</button>
					<h5 class="modal-title" id="exampleModalLabel">حذف گزارش</h5>
				</div>
				<form method="post" id="delete-form">
					{% csrf_token %}
					<div class="modal-body">
						<p class="float-right">
							آیا واقعا می خواهید گزارش 
							<code>
								<strong id="delete-name"></strong>
							</code>
							را حذف کنید؟
						</p>
					</div>
					<div class="modal-footer float-right">
						<button type="button" class="btn btn-secondary" data-dismiss="modal">انصراف</button>
						<button type="submit" class="btn btn-danger">حذف</button>
					</div>
				</form>
			</div>
		</div>
	</div>


{% endblock %}

{% block scripts %}
	<link href="{% static 'vendors/datatables/css/datatables.min.css' %}" rel="stylesheet">
    <script src="{% static 'vendors/datatables/js/datatables-document.min.js' %}"></script>
	<script src="{% static 'vendors/datatables/js/datatables.bootstrap4.min.js' %}"></script>

	<script>
		var table;
		$(document).ready(function () {
			table = $('.dataTables-example').DataTable({
				pageLength: 100,
				responsive: true,
				dom: 'lTfgitp<"float-right"B>',
                buttons: [
					{
						extend: 'print',
                        pageSize: 'A4',
                        text: '<button class="btn btn-lg btn-outline-danger"><i class="fa fa-print"></i> خروجی PDF</button>',
						className: 'bg-transparent',
                        title: '',

						exportOptions: {
							columns: [0, 1, 2, 4, 5, 6, 7],
							{#stripHtml: true#}
						},
                        customize: function (win) {
							$(win.document.body).addClass('white-bg');
							$(win.document.body).find('thead')
								.css('color', 'black')
								.css('font-family', 'VazirFD')
								.prepend("<tr><th colspan='8'>" +
									"<img src='http://127.0.0.1:8000/static/img/logo.png' class='float-left obj-fit-contain' style='position:relative;width:15%' />" +
									"<img src='http://127.0.0.1:8000/static/img/sepah_balck.png' class='float-right obj-fit-contain' style='position:relative;width:15%' />" +
									"<h2 class='text-center'><u><b>فهرست گزارش های فنی محققین و مدیران</b></u></h2>" +
									"</th>" +
									"</tr>");
                            $(win.document.body).find('tbody')
								.css('color', 'black')
								.css('font-family', 'VazirFD')
								.append("<tr><th colspan='8'>" +
                                    "<br><br><br>" +
                                    "<h2 class='text-center' ><b>مدیر دانش ساتخ ندسا</b></h2>" +
                                    "<h3 class='text-center' >محل مهر و امضا</h3" +
                                    "<br><br><br>" +
                                    "</tr>")

							$(win.document.body).find('table')
								.addClass('compact')
								.css('font-size', 'inherit')
								.css('color', 'black')
								.css('border-color', 'transparent')
								.css('font-family', 'VazirFD');

							$(win.document.body).find('td:eq(0)')
								.css('width', '5%');
							$(win.document.body).find('td:eq(7)')
								.css('width', '15%');
							$(win.document.body).find('td:nth-child(odd)')
								.css('background-color', '#f2f2f2');
						}
					},
                    {
						extend: 'excelHtml5',
                        text: '<button class="btn btn-lg btn-outline-success"><i class="fa fa-print"></i> خروجی Excel</button>',
						className: 'bg-transparent',
                        title: '',
						filename: 'reports',
						exportOptions: {
							columns: [ 1, 2, 3,4, 5, 6, 7],
						}
					},
                    {
                        text: '<button class="btn btn-lg btn-outline-primary"><i class="fa fa-print"></i> بارگزاری Excel</button>',
						className: 'bg-transparent',
                        title: '',
						action: function ( e, dt, node, config ) {
                            location.replace("{% url 'documents:import' document_type='Report' %}")
                        }
					}
				]
			});

		});

		$('#producer').on('producer', function () {
                table.column(4).search(this.value).draw();
		});
		$('#center').on('keyup', function () {
			table.column(7).search(this.value).draw();
		});
		$('#presentation_date').on('keyup', function () {
			table.column(5).search(this.value).draw();
		});

		$('#delete-modal').on('show.bs.modal', function (e) {
			id = $(e.relatedTarget).data('cid');
			tr = $('#c-tr-' + id);
			$('#delete-name').text(tr.find("td:eq(1)").text());
			delete_url = "{% url 'documents:report_delete' pk=0 %}";
			$('#delete-form').attr('action', delete_url + id);
		});

		// this is the id of the form
		$("#delete-form").submit(function (e) {
			var form = $(this);
			var url = form.attr('action');

			$.ajax({
				type: "POST",
				url: url,
				data: form.serialize(), // serializes the form's elements.
				success: function (data) {
					location.reload();
				}
			});
			e.preventDefault(); // avoid to execute the actual submit of the form.
		});
	</script>
{% endblock %}